name: snapd
version: 0.1.1

description:
  Provides a client to access snapd, which allows you to manage, search and install snaps on a Linux system.

homepage: https://github.com/canonical/snapd.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.8
  test_cov: ^1.0.1

