name: snapd
version: 0.4.9

description:
  Provides a client to access snapd, which allows you to manage, search and install snaps on a Linux system.

homepage: https://github.com/canonical/snapd.dart

environment:
  sdk: '>=2.17.0 <3.0.0'

platforms:
  linux:

dependencies:
  collection: ^1.15.0
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.8
  test_cov: ^1.0.1

